
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'PokeHelper'
    ports:
      - '5432:5432'
    volumes:
      - pg:/var/lib/postgresql
volumes:
  pg: {}